version: '3'

services:
  web:
    build:
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/responsive_checker_app/
      # - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    container_name: responsive_checker_app
  db:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    tty: true

volumes:
  mysql_data:
  bundle: